Exdened it a bit
rollun-com/rollun-callback pull request #86
Opened 2022-11-03 12:06 UTC by mikola-rollun

2022-11-04 15:05 UTC, misha-rollun requested changes

2022-11-04 15:05 UTC, misha-rollun commented on docs/index.md
> +Всі типи колбеків можуть бути викликані вебхуком без додаткової конфігурації.
Краще написати якось, що після конфігурації роута усі типи калбеків можуть бути викликані за своїм ім'ям по спеціальному url. Тому що з цього речення можна подумати що ніяка конфігурація не потрібна, хоча потрібна конфігурація роутинга

2022-11-04 15:05 UTC, misha-rollun commented on docs/index.md
> +#### Якщо callback використовує сервіси, то його створення потрібно робити через фабрику, котра передасть сервіси в конструктор
Тоді вже варто написати, що також можна робити без фабрики через InsideConstruct

2022-11-04 15:42 UTC, mikola-rollun commented on docs/index.md
> +Всі типи колбеків можуть бути викликані вебхуком без додаткової конфігурації.
Комітнув

2022-11-04 15:42 UTC, mikola-rollun commented on docs/index.md
> +#### Якщо callback використовує сервіси, то його створення потрібно робити через фабрику, котра передасть сервіси в конструктор
комітнув

2022-11-07 13:46 UTC, misha-rollun approved these changes

2022-11-07 13:46 UTC, merged